# Generated by Django 5.2 on 2025-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_alter_orden_envio_total_orderaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='delivery_method',
            field=models.CharField(choices=[('SHIPPING', 'Envío'), ('PICKUP', 'Retiro')], default='SHIPPING', max_length=40),
        ),
    ]
