# Generated by Django 5.2 on 2025-04-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_alter_orden_delivery_method'),
        ('profiles', '0006_alter_address_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ciudad'),
        ),
    ]
