# Generated by Django 5.2 on 2025-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0008_orden_fecha_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='num_orden',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
