# Generated by Django 5.2 on 2025-05-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0009_orden_num_orden'),
    ]

    operations = [
    ]
