# Generated by Django 5.2 on 2025-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0010_auto_20250511_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='delivery_method',
            field=models.CharField(choices=[('SHIPPING', 'Envío'), ('PICKUP', 'Retiro')], default='PICKUP', max_length=40),
        ),
    ]
