# Generated by Django 5.2 on 2025-04-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_comuna_remove_userprofile_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
    ]
