# Generated by Django 5.2 on 2025-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_ciudad_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='num_direccion',
            field=models.CharField(),
        ),
    ]
