# Generated by Django 5.2 on 2025-04-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_address_num_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ciudad'),
        ),
    ]
