# Generated by Django 5.2 on 2025-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_address_ciudad'),
    ]

    operations = [
    ]
