# Generated by Django 5.2 on 2025-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20250511_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='valor_envio',
            field=models.IntegerField(default=0),
        ),
    ]
