# Generated by Django 5.2 on 2025-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_productos_cartproduct'),
        ('products', '0008_brand_created_at_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(through='cart.CartProduct', to='products.product'),
        ),
    ]
