# Generated by Django 5.2 on 2025-04-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_category_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
