# Generated by Django 5.2 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
