# Generated by Django 5.2 on 2025-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_created_at_category_created_at'),
    ]

    operations = [
    ]
